FROM alpine:3.7
LABEL maintainer "me@jowj.net"

RUN apk update

RUN apk add \
    python3 \ 
    python-dev    

RUN python3 -m pip install --upgrade pip

RUN python3 -m pip install slackclient

COPY ./ ./

CMD python3 ./mojojojo-bot.py
