FROM alpine:3.9
LABEL maintainer "me@jowj.net"

RUN apk update

RUN apk add \
    python3 \ 
    python3-dev \
    libffi-dev

RUN apk add --no-cache curl python pkgconfig python-dev openssl-dev libffi-dev musl-dev make gcc

RUN pip3 install --upgrade pip

RUN pip3 install --upgrade setuptools

RUN pip3 install slackclient<2.0.0

COPY ./ ./

CMD python3 ./mojojojo-bot.py
